### ISSUE TITLE
Use .bib file for references

### ISSUE THREAD

**Issue by kescobo** [afarrellsherman/Woolf#2]
Using [BibTeX format](http://www.bibtex.org/Format/) for your references will make it easier to pass around / import into reference managers. Basically any citation manager (eg EndNote) will make this file for you.

**Comment by afarrellsherman** [comment]
How do you export as a BibTeX file?  I can't seem to make it work form my version of endnote

**Comment by kescobo** [comment]
https://www.reed.edu/cis/help/LaTeX/EndNote.html
