### ISSUE TITLE
Version with scikit-learns accuracy features

### ISSUE THREAD

**Issue by afarrellsherman** [afarrellsherman/Woolf#3]
This is what I am currently working on, it needs GridSearchCV implementation to be fixed (I think it would be good to do?) and AUC to be added (I want to add this)

https://github.com/afarrellsherman/Woolf/blob/master/kNN_crossValidation.py

**Comment by kescobo** [comment]
This is also addressed now, right?

**Comment by afarrellsherman** [comment]
done
